// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wimovblvuqhgajukqemm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpbW92Ymx2dXFoZ2FqdWtxZW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjA4MDAsImV4cCI6MjA2MDY5NjgwMH0.nzLzNRMry2PmmI6hRXTiw8y_sr_kq9bgAauiTJ3_Tlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);